name: Deploy Influxdb Container
env:
  AZURE_REPOSITORY: influx.db
  AZURE_DOCKER_IMAGE_TAG: 1.7.${{ github.run_number }}-buildx-${{ github.sha }}
  BUILD_NUMBER: ${{ github.run_number }}
  DOCKER_FILE: docker/influxdb/Dockerfile
  BRANCH_NAME: "${{ github.ref_name }}"
  DNS_LABEL_NAME: "azureconnectedservicesinflux"
  CONTAINER_NAME: "influxdb"
  CONTAINER_PORTS: "8083 8086 8088"
on:
  workflow_dispatch:

  push:
    paths:
      - "docker/influxdb/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Docker Image Uri
        run: echo $AZURE_DOCKER_IMAGE

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build and push image"
        id: build-image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f ${{ env.DOCKER_FILE }} \
                --build-arg BUILD_DATE=${{ steps.date.outputs.date }} \
                --build-arg BUILD_NUMBER=${{ env.BUILD_NUMBER }} \
                -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_REPOSITORY}}:latest \
                -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_REPOSITORY}}:${{ env.AZURE_DOCKER_IMAGE_TAG }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_REPOSITORY}} --all-tags

  deploy:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      app-url: ${{ steps.deploy-container.outputs.app-url }}

    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        id: deploy-container
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          location: "eastus"
          dns-name-label: ${{ env.DNS_LABEL_NAME }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_REPOSITORY}}:${{ env.AZURE_DOCKER_IMAGE_TAG }}
          name: ${{ env.CONTAINER_NAME }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: ${{ env.CONTAINER_PORTS }}
          azure-file-volume-share-name: "connectedservices-db"
          azure-file-volume-account-name: "azureconnectedservices01"
          azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
          azure-file-volume-mount-path: /var/lib/influxdb
